version: '3.4'
services:
   caddy:
    image: caddy:2.4.6-alpine
    container_name: webserver
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nc-water-supply:/srv
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
   web:
    image: fraunhoferiosb/frost-server:latest
    environment:
      - serviceRootUrl=https://api.boerne-water-dashboard.internetofwater.app/api
      - http_cors_enable=true
      - http_cors_allowed_origins=*
      - http_cors_allowed_methods=GET,HEAD,POST,PATCH,DELETE,OPTIONS
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
      - persistence_autoUpdateDatabase=true
      - persistence_persistenceManagerImplementationClass=de.fraunhofer.iosb.ilt.sta.persistence.pgjooq.imp.PostgresPersistenceManagerString
      - persistence_idGenerationMode=ServerAndClientGenerated
#      - auth_provider=de.fraunhofer.iosb.ilt.frostserver.auth.basic.BasicAuthProvider
#      - auth_db_driver=org.postgresql.Driver
#      - auth_db_username=sensorthings
#      - auth_db_password=ChangeMe
#      - auth_autoUpdateDatabase=true
    ports:
      - 8080:8080
      - 1883:1883
    depends_on:
      - database
   database:   
    container_name: frostdb
    image: kartoza/postgis:14-3.2
    environment:
        - POSTGRES_DB=sensorthings
        - POSTGRES_USER=sensorthings
        - POSTGRES_PASS=ChangeMe
        - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting,uuid-ossp
    volumes:
        - postgis_volume:/var/lib/postgresql/data
   rstudio:
    image: rocker/rstudio:4.1.2
    environment:
      - PASSWORD=rstudio1
    ports:
      - 8787:8787
volumes:
   postgis_volume: